### ISSUE TITLE
Which feature should i adopt in to the stable?

### ISSUE THREAD

**Issue by MuhammedKpln** [MuhammedKpln/chob#11]
So right now we have two different features that you can enable with arguments. So which on of them(or maybe both) that you want to use it without adding any extra arguments.

Here is the features im talking about:
* [Cache Manager](https://github.com/MuhammedKpln/chob/releases/tag/0.7)
* [Automatically download the AppImage applications](https://github.com/MuhammedKpln/chob/releases/tag/0.5)

**Comment by nigelwarning** [comment]
Still possible to do the download Appimage thing? Just found out about your app, works great.

**Comment by MuhammedKpln** [comment]
> Still possible to do the download Appimage thing? Just found out about your app, works great.


That feature is still experimental but i would love to bring that on to the stable version as soon as possible.
