### ISSUE TITLE
Does not find e2designer

### ISSUE THREAD

**Issue by probonopd** [MuhammedKpln/chob#2]
Does not find `e2designer` despite that it is in https://appimage.github.io/feed.json.

```
me@host:~$ '/home/me/Downloads/chob-linux.bundle-linux' e2designer
🔎 Searching e2designer on repositories.
Couldn't find any package with name of e2designer
```

**Comment by MuhammedKpln** [comment]
That's probably because of the database i'm using is not up-to-dated. As you said on previous issue, i will change appimage repo to the  `https://appimage.github.io/feed.json` soon.

**Comment by MuhammedKpln** [comment]
As we implemented this feature, we can now close the issue.
