### ISSUE TITLE
Getting errors because of old configs

### ISSUE THREAD

**Issue by algent-al** [MuhammedKpln/chob#22]
With the new release, I think you should mention that the old `~/chob` folder should be deleted.
```
$ chob vlc
⚡ Your cache will now be enabled.
Searching for vlc in application repos..
Traceback (most recent call last):
  File "cli.py", line 36, in <module>
  File "cli.py", line 31, in main
  File "main.py", line 29, in __init__
  File "main.py", line 53, in __fetch_data
  File "serializer.py", line 48, in serialize_appimage_data
TypeError: string indices must be integers
[26817] Failed to execute script cli
```

EDIT: I use `chob` with alias `alias chob='chob --enableCache'`

**Comment by MuhammedKpln** [comment]
Well it should be compatible with the old chob folder. As always it works on my computer 😅

Can i see your old config file?

**Comment by algent-al** [comment]
Started over by deleting the ~/chob folder:
The content of `config.json` file switches from `{}` to `{"cache_enabled": true}`. but here both `chob` and `chob-old` are working fine. `chob-old` is chob version 0.9

Found that the buggy `config.json` file have this content:
`{"cacheEnabled": true, "cache_enabled": true}`

**Comment by MuhammedKpln** [comment]
Oh i see why, thanks for your feedback!

**Comment by MuhammedKpln** [comment]
With the new version of Chob that uses Go, we no longer use config file.
