### ISSUE TITLE
hide `chob` config folder

### ISSUE THREAD

**Issue by algent-al** [MuhammedKpln/chob#24]
Having `chob` config folder in Home, I don't think is a good practice.
I suggest using it as `.chob` or move it to `.config/chob`.

**Comment by MuhammedKpln** [comment]
That is because it saves appimages on chob folder. But I'll take a look at better structure.

**Comment by algent-al** [comment]
> That is because it saves appimages on chob folder.

Oh, that is why. Made a test by installing an AppImage and yes it was saved in the `chob` folder. So the real problem here is where to save the AppImage files.

**Comment by martin-braun** [comment]
@MuhammedKpln I think it would be better to follow [the official suggestion](https://docs.appimage.org/user-guide/faq.html#question-where-do-i-store-my-appimages) and store those images in `$HOME/Applications/` instead. `chob`s config should be hidden indeed. +1
