### ISSUE TITLE
10 processes

### ISSUE THREAD

**Issue by algent-al** [MuhammedKpln/chob#5]
Hi!
Looking at htop I see there are 10 processes opened for chob-linux. I did just a test by searching for vlc.
Is this a normal behavior?

![chob-linux](https://user-images.githubusercontent.com/46356616/58789328-29b5c600-85ee-11e9-9f46-fe2165fb4ddf.png)

**Comment by MuhammedKpln** [comment]
It seems to be normal behaviour of nodejs. Tested without bundle it to one size, still get the same results.

Same on yarn package manager too, creates multiple processes.
